# Generated by Django 4.2.30 on 2026-09-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(help_text='Ne hakkında kararsızsın? (en az 10 karakter)', max_length=300, verbose_name='Soru')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anketler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=200, verbose_name='Seçenek Metni')),
                ('oy_sayisi', models.PositiveIntegerField(default=0, verbose_name='Oy Sayısı')),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='anketler.anket', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
            },
        ),
        migrations.CreateModel(
            name='Oy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oturum_id', models.CharField(help_text='Anonim kullanıcılar için session key', max_length=64, verbose_name='Oturum ID')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Oy Tarihi')),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oylar', to='anketler.anket', verbose_name='Anket')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oylar', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oylar', to='anketler.secenek', verbose_name='Seçenek')),
            ],
            options={
                'verbose_name': 'Oy',
                'verbose_name_plural': 'Oylar',
            },
        ),
        migrations.AddConstraint(
            model_name='oy',
            constraint=models.UniqueConstraint(fields=('anket', 'oturum_id'), name='unique_oturum_oy'),
        ),
    ]
